# Generated by Django 4.2.7 on 2024-04-28 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Клиент')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Sorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorts_name', models.CharField(max_length=50)),
                ('sorts_position', models.IntegerField()),
                ('sorts_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.category')),
            ],
            options={
                'verbose_name': 'Сорт',
                'verbose_name_plural': 'Сорта',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sales/image/', verbose_name='Фотография')),
                ('phone', models.CharField(blank=True, max_length=18, null=True, verbose_name='Номер телефона')),
                ('geo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('email_push', models.BooleanField(default=False, verbose_name='Подписка по email')),
                ('phone_push', models.BooleanField(default=False, verbose_name='Подписка по SMS')),
                ('cart', models.IntegerField(blank=True, null=True, verbose_name='Номер дебетовой карты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='Скидка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sales/image/', verbose_name='Фотография')),
                ('archived', models.BooleanField(default=False, verbose_name='Архив')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.category', verbose_name='Категория')),
                ('sort', smart_selects.db_fields.GroupedForeignKey(group_field='sorts_category', on_delete=django.db.models.deletion.CASCADE, to='bot.sorts', verbose_name='Сорта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Каталоги',
                'ordering': ['name', 'price'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='bot.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='bot.product', verbose_name='Продукт')),
            ],
        ),
    ]
